In [1]:
1 #integer

1

In [4]:
int (1) #same as the previous code

1

In [5]:
1.0 #float

1.0

In [6]:
float (1.0) #same as the previous code

1.0

In [7]:
int ("1") #converting string to int

1

In [8]:
int (1.6) #converting float to int

1

In [10]:
int (True) #converting boolean to int

1

In [11]:
a = 1 + 2 #create and assign to a variable; then print
print (a)

3


In [12]:
range (0,10) #0,1,2,3,4,5,6,7,8,9

range(0, 10)

In [13]:
range 10

SyntaxError: invalid syntax (3775711695.py, line 1)

In [14]:
range (10) #same as the previous code

range(0, 10)

In [19]:
b = range(0,10) #assign the range to the variable and use a for loop to access; then print
for i in b:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
L = [1,2,3] #create a list
print (L)

[1, 2, 3]


In [21]:
L[0], L[1], L[2] #indexing

(1, 2, 3)

In [22]:
L[-1], L[-2], L[-3] #indexing displayed in the reverse order

(3, 2, 1)

In [24]:
L[0] = 4 #list are mutable ie. the changed data is replaced at the same index
L[0]

4

In [30]:
L = [1, 2, 3]
try:
    L[3] = 4  # not allowed, tuples are immutable
except Exception as e:
    print(e)

list assignment index out of range


In [31]:
T = (1, 2, 3) #create tuples
try:
    T[0] = 4  # not allowed, tuples are immutable
except Exception as e:
    print(e)

'tuple' object does not support item assignment


In [32]:
T = (1, 2, 3)
T[0] = 4  # not allowed, tuples are immutable; 'tuple' object does not support item assignment


TypeError: 'tuple' object does not support item assignment

In [33]:
S = set()
print (S)

set()


In [35]:
S.add(1) # S= {1}
print (S)

{1}


In [36]:
S.add (1) #set doesn't accept repeated items
print (S)

{1}


In [38]:
S.add (2) # S = {1,2}
print (S)

{1, 2}


In [39]:
D = {'a':1, 'b' :2}
print (D)

{'a': 1, 'b': 2}


In [40]:
D.keys()

dict_keys(['a', 'b'])

In [41]:
D.values()

dict_values([1, 2])

In [42]:
D.items()

dict_items([('a', 1), ('b', 2)])

In [43]:
D ['a'] #access by key


1

In [44]:
del D ['a']

In [45]:
D ['a']

KeyError: 'a'

In [46]:
D. keys()

dict_keys(['b'])

In [48]:
S = "Hello World"
print (S)

Hello World


In [49]:
S [0:10]

'Hello Worl'

In [56]:
S [-2]

'l'

In [58]:
try:
    S [2] = 'h'
except Exception as e:
    print (e)

'str' object does not support item assignment


In [60]:
S = 'H' + S[1:] # reconstruct S with new first character and use indexing [1:]
print (S)

Hello World


In [62]:
S = 'U' + S[2:]
print (S)

Ullo World


In [63]:
S [0:10]

'Ullo World'

In [64]:
S [0:]

'Ullo World'

In [65]:
S [-1:]

'd'

In [66]:
S[-1:-4:2]

''

In [67]:
S[1:7:3]

'l '

In [68]:
S[:6]

'Ullo W'

In [69]:
S [0]

'U'

In [71]:
L1 = [1,2,3]
L2 = [element*2 for element in L1]
print (L2)

[2, 4, 6]


In [72]:
!pip install numpy

In [74]:
import numpy as np

In [79]:
a = np.zeros(10)
print ('a=\n:', a)

a=
: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [80]:
b = np.ones(10)
print ('b=\n' , b)

b=
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [81]:
print ('a-b' ,a-b)

a-b [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [86]:
c= np.ones((3,2))
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [89]:
c[0,0] = 1; c[0,1] = 2
print (c)

[[1. 2.]
 [1. 1.]
 [1. 1.]]


In [90]:
d= np.array([[1,2],[4,5]])
print (d)

[[1 2]
 [4 5]]


In [94]:
print ('c!=d\n', c!= d)

c!=d
 True


C:\Users\sheet\AppData\Local\Temp\ipykernel_8424\369399964.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print ('c!=d\n', c!= d)


In [95]:
print('(c==d).sum()\n', (c==d).sum())

C:\Users\sheet\AppData\Local\Temp\ipykernel_8424\2827277485.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('(c==d).sum()\n', (c==d).sum())


AttributeError: 'bool' object has no attribute 'sum'

In [96]:
print (c,d)

[[1. 2.]
 [1. 1.]
 [1. 1.]] [[1 2]
 [4 5]]


In [97]:
c = np.array([[1,2],[3,4]])
print (c)

[[1 2]
 [3 4]]


In [98]:
c = np.array([[1,2],[4,5]])
print (c)

[[1 2]
 [4 5]]


In [99]:
print ('c==d\n', c==d)

c==d
 [[ True  True]
 [ True  True]]


In [101]:
print('c==d.sum()\n', (c==d).sum())

c==d.sum()
 4
